### PR TITLE
[Feature] Add Mid-Air Tech variant

### PR DESCRIPTION
**Pull request by balt-dev**
This variant allows for inputting supers, hypers, etc. in midair. Goes well with wall-less wallbounces.

https://github.com/maddie480/ExtendedVariantMode/assets/59123926/c1baec54-8bb2-4473-92f5-149b01b3e703

### CODE REVIEW

**Comment by balt-dev** [comment]
Another video:

Uploading ext-2024-05-02_21.12.41.mp4…

**Comment by balt-dev** [comment]
Another video:

https://github.com/maddie480/ExtendedVariantMode/assets/59123926/f8d0284a-2bd7-4230-88d4-5b3b82cb5e9f

**Comment by maddie480** [comment]
uh, did you forget to commit the actual MidairTech.cs file? ^^'

**Comment by balt-dev** [comment]
lmao i did! good catch

**Comment by balt-dev** [comment]
@maddie480 fixed!

**Pull request merged**
